name: Generate QR Code from JSON

on:
  push:
    branches:
      - main # main ブランチへのプッシュをトリガーにする場合
    paths:
      - 'blob/main/WorkSet/data.json' # data.json が変更された場合のみトリガー

jobs:
  build:
    runs-on: ubuntu-latest # 実行環境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # リポジトリのコードをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用する Node.js のバージョンを指定

      - name: Install dependencies
        run: npm install qrcode # QR コード生成ライブラリをインストール

      - name: Generate QR Code
        run: node scripts/generate-qrcode.js # 作成したスクリプトを実行

      - name: Commit and push QR Code
        uses: EndBug/add-and-commit@v9 # QR コードをコミット・プッシュするアクション
        with:
          message: "feat: Update QR code for data.json" # コミットメッセージ
          add: 'blob/main/WorkSet/qrcode.png' # 追加するファイル
          author_name: "GitHub Actions" # コミットの作成者名
          author_email: "actions@github.com" # コミットの作成者メールアドレス
          commit_author: "github-actions[bot] <actions@github.com>" # コミットの Author ヘッダー
          branch: main # プッシュするブランチ
