name: Generate QR Code from JSON

on:
  push:
    branches:
      - main  # このワークフローをトリガーするブランチを指定
    paths:
      - 'WorkSet/data.json'  # 監視対象のJSONファイルのパスを指定

jobs:
  generate-qr-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install qrcode

      - name: Generate QR Code
        id: generate_qr
        run: |
          node -e "
            const fs = require('fs');
            const qrcode = require('qrcode');
            const data = fs.readFileSync('WorkSet/data.json', 'utf8');
            qrcode.toFile('WorkSet/qrcode.png', data, {
              errorCorrectionLevel: 'H'
            }, err => {
              if (err) throw err;
              console.log('QR code generated successfully!');
            });
          "

      - name: Commit and push QR code
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add WorkSet/qrcode.png
          git commit -m 'feat: Generate QR code from data.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
