name: Generate QR Code from JSON

on:
  push:
    branches:
      - main
    paths:
      - 'WorkSet/data.json'

jobs:
  generate-qr-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install qrcode

      - name: Generate QR Code
        run: |
          # Make sure the path in your Node.js script is correct
          # For example, if data.json is at the root of WorkSet/, use 'WorkSet/data.json'
          node scripts/generate-qrcode.js
        # Assuming your Node.js script is in 'scripts/generate-qrcode.js'
        # and inside that script, you've corrected the path to 'WorkSet/data.json'

      - name: Commit and push QR code
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add WorkSet/qrcode.png
          git commit -m 'feat: Generate QR code from data.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
